changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: "Features"
      labels:
        - feature
        - enhancement
    - title: "Fixes"
      labels:
        - bug
        - fix
    - title: "Performance"
      labels:
        - perf
        - optimization
    - title: "Documentation"
      labels:
        - docs
    - title: "CI/CD"
      labels:
        - ci
        - release
    - title: "Other Changes"
      labels:
        - "*"
